version: "0.2"
ignorePaths:
  - mkdocs.yml
  - cspell.config.yaml
dictionaryDefinitions: []
dictionaries: []
words:
  - BLDC
  - datasheet
  - Datasheets
  - Micromod
  - Mosfets
  - Pullup
  - Umeda
ignoreWords: []
import: []
